POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1ZjQ0NTJjMDY3MzU0YzA4OGZjNjZmMTQiLCJpYXQiOjE1OTgzODQ2MjJ9.3lXcCgrlAv8i1VC6WeYUcZ7I_dSqwca_ATco-p0YQeU

{
  "title": "New test blog",
  "author": "root",
  "url": "www.sevak.com/newUser"
}
